/**
 * One-line discovery copy from published Decision Engine fields.
 * Interpolates numbers only — no LLM, no invented markets.
 */

import { signedPct } from "@/lib/apex-brain/format";
import type { ApexOpportunity } from "@/lib/apex-opportunities/types";

function firstSentence(text: string): string | null {
  const trimmed = text.trim();
  if (!trimmed) return null;
  const match = trimmed.match(/^[^.!?]+[.!?]?/);
  const sentence = match?.[0]?.trim();
  if (!sentence) return null;
  return /[.!?]$/.test(sentence) ? sentence : `${sentence}.`;
}

export function opportunityBlurb(row: ApexOpportunity): string {
  const ev = row.expectedValue;
  const hasEv = ev != null && Number.isFinite(ev);

  if (row.positiveEdge && hasEv && ev > 0) {
    return `Positive expected value (${signedPct(ev)}) generated by market inefficiency.`;
  }

  if (hasEv && ev < 0) {
    return `Negative expected value (${signedPct(ev)}); the published price does not beat the model.`;
  }

  if (row.bookmakerOdds == null) {
    const score =
      row.score == null ? "unavailable" : String(Math.round(row.score));
    const confidence =
      row.confidence == null ? "unavailable" : String(Math.round(row.confidence));
    return `APEX Score ${score} with ${confidence} confidence; no current bookmaker odds are published.`;
  }

  if (hasEv && ev === 0) {
    return "Expected value is flat at this price; the engine does not find a market inefficiency.";
  }

  return (
    firstSentence(row.explanation) ??
    `Engine verdict ${row.verdictLabel ?? "unavailable"} at score ${row.score == null ? "unavailable" : Math.round(row.score)}.`
  );
}
