import { describe, expect, it } from "vitest";
import { opportunityBlurb } from "@/lib/apex-opportunities/blurb";
import {
  DEFAULT_DISCOVERY_FILTERS,
  discoveryDashboardStats,
  discoveryPriority,
  discoveryRecommendation,
  filterDiscovery,
  marketDisplayName,
  sortDiscovery,
} from "@/lib/apex-opportunities/discovery";
import { opportunityFixture } from "@/lib/apex-opportunities/fixture";

describe("APEX Opportunities discovery ranking", () => {
  const elite = opportunityFixture();
  const strong = opportunityFixture({
    fixtureId: "strong",
    score: 74,
    stars: 4,
    verdict: "strong_bet",
    verdictLabel: "Strong Bet",
    recommendation: "Strong Bet",
    expectedValue: 0.11,
    kellyPct: 4.2,
    riskScore: 40,
    riskBand: "medium",
    kickoffAt: "2026-08-27T19:00:00.000Z",
    leagueName: "La Liga",
  });
  const avoid = opportunityFixture({
    fixtureId: "avoid",
    score: 66,
    stars: 1,
    confidence: 37,
    expectedValue: 0.04,
    kellyPct: 0,
    verdict: "avoid",
    verdictLabel: "Avoid",
    recommendation: "Avoid",
    positiveEdge: true,
    riskScore: 70,
    riskBand: "high",
    kickoffAt: "2026-08-27T12:00:00.000Z",
  });

  it("maps engine verdicts to visual priority and recommendation badges", () => {
    expect(discoveryPriority(elite)).toEqual({
      stars: 5,
      label: "Elite Opportunity",
      shortLabel: "Elite",
    });
    expect(discoveryPriority(strong).label).toBe("Strong");
    expect(discoveryPriority(avoid).label).toBe("Avoid");
    expect(discoveryRecommendation(elite)).toBe("STRONG BET");
    expect(discoveryRecommendation(strong)).toBe("BET");
    expect(discoveryRecommendation(avoid)).toBe("SKIP");
    expect(marketDisplayName("1x2")).toBe("1X2");
  });

  it("ranks the full analysed set by default, including Avoid", () => {
    const ranked = filterDiscovery([avoid, elite, strong]);
    expect(ranked.map((row) => row.fixtureId)).toEqual([
      "1035089",
      "strong",
      "avoid",
    ]);
  });

  it("sorts by EV, Kelly, risk and kickoff without changing scores", () => {
    const rows = [elite, strong, avoid];
    expect(
      sortDiscovery(rows, "ev").map((row) => row.fixtureId),
    ).toEqual(["strong", "1035089", "avoid"]);
    expect(
      sortDiscovery(rows, "kelly").map((row) => row.fixtureId),
    ).toEqual(["strong", "1035089", "avoid"]);
    expect(sortDiscovery(rows, "risk")[0]?.fixtureId).toBe("1035089");
    expect(sortDiscovery(rows, "kickoff")[0]?.fixtureId).toBe("avoid");
    expect(elite.score).toBe(82);
  });

  it("filters league, market, min score, risk, recommendation, kickoff and favorites", () => {
    const rows = [elite, strong, avoid];
    expect(
      filterDiscovery(rows, {
        ...DEFAULT_DISCOVERY_FILTERS,
        league: "La Liga",
      }).map((row) => row.fixtureId),
    ).toEqual(["strong"]);

    expect(
      filterDiscovery(rows, {
        ...DEFAULT_DISCOVERY_FILTERS,
        minScore: 80,
      }).map((row) => row.fixtureId),
    ).toEqual(["1035089"]);

    expect(
      filterDiscovery(rows, {
        ...DEFAULT_DISCOVERY_FILTERS,
        recommendation: "SKIP",
      }).map((row) => row.fixtureId),
    ).toEqual(["avoid"]);

    expect(
      filterDiscovery(rows, {
        ...DEFAULT_DISCOVERY_FILTERS,
        risk: "high",
      }).map((row) => row.fixtureId),
    ).toEqual(["avoid"]);

    expect(
      filterDiscovery(rows, {
        ...DEFAULT_DISCOVERY_FILTERS,
        kickoff: "evening",
      }).map((row) => row.fixtureId),
    ).toEqual(["strong"]);

    expect(
      filterDiscovery(
        rows,
        { ...DEFAULT_DISCOVERY_FILTERS, favoritesOnly: true },
        ["avoid"],
      ).map((row) => row.fixtureId),
    ).toEqual(["avoid"]);
  });

  it("summarises the day's scan independently of row filters", () => {
    const stats = discoveryDashboardStats([elite, strong, avoid]);
    expect(stats.today).toBe(3);
    expect(stats.elite).toBe(1);
    expect(stats.averageConfidence).toBeCloseTo((72 + 72 + 37) / 3);
    expect(stats.highestKelly).toBe(4.2);
  });
});

describe("opportunity blurb", () => {
  it("explains positive EV from published inefficiency", () => {
    expect(opportunityBlurb(opportunityFixture())).toBe(
      "Positive expected value (+6.0%) generated by market inefficiency.",
    );
  });

  it("explains negative EV without inventing a market", () => {
    expect(
      opportunityBlurb(
        opportunityFixture({
          positiveEdge: false,
          expectedValue: -0.05,
        }),
      ),
    ).toBe(
      "Negative expected value (-5.0%); the published price does not beat the model.",
    );
  });

  it("notes missing bookmaker odds", () => {
    expect(
      opportunityBlurb(
        opportunityFixture({
          bookmakerOdds: null,
          positiveEdge: false,
          expectedValue: null,
        }),
      ),
    ).toMatch(/no current bookmaker odds/i);
  });
});
