/**
 * Deterministic synthetic rows for harness tests. Not evidence for policy choice.
 */

import {
  CALIBRATION_RECONSTRUCTION_VERSION,
  CALIBRATION_SCHEMA_VERSION,
  type CalibrationRow,
  type ReconstructionFixture,
} from "@/lib/debug/calibration/types";

function row(
  partial: Omit<CalibrationRow, "schemaVersion" | "reconstructionVersion" | "market"> & {
    market?: CalibrationRow["market"];
  },
): CalibrationRow {
  return {
    schemaVersion: CALIBRATION_SCHEMA_VERSION,
    reconstructionVersion: CALIBRATION_RECONSTRUCTION_VERSION,
    market: partial.homeOdds != null ? "1x2" : null,
    ...partial,
  };
}

export function createSyntheticCalibrationRows(): CalibrationRow[] {
  return [
    row({
      fixtureId: "syn-played-0-home-win",
      kickoff: "2024-08-10T15:00:00.000Z",
      competitionId: "syn-league",
      competitionName: "Synthetic League",
      season: "2024",
      category: "mens",
      homeTeamId: "home-new",
      homeTeamName: "New Home",
      awayTeamId: "away-new",
      awayTeamName: "New Away",
      homePlayedBefore: 0,
      homeWinsBefore: 0,
      homeGfBefore: 0,
      homeGaBefore: 0,
      awayPlayedBefore: 0,
      awayWinsBefore: 0,
      awayGfBefore: 0,
      awayGaBefore: 0,
      actualHomeGoals: 1,
      actualAwayGoals: 0,
      actualOutcome: "home",
      bookmaker: "SyntheticBook",
      homeOdds: 1.5,
      drawOdds: 4,
      awayOdds: 6,
      oddsObservedAt: null,
      oddsTiming: "unknown",
    }),
    row({
      fixtureId: "syn-played-1-favorite-correct",
      kickoff: "2024-08-17T15:00:00.000Z",
      competitionId: "syn-league",
      competitionName: "Synthetic League",
      season: "2024",
      category: "mens",
      homeTeamId: "home-hot",
      homeTeamName: "Hot Home",
      awayTeamId: "away-cold",
      awayTeamName: "Cold Away",
      homePlayedBefore: 1,
      homeWinsBefore: 1,
      homeGfBefore: 1,
      homeGaBefore: 0,
      awayPlayedBefore: 1,
      awayWinsBefore: 0,
      awayGfBefore: 0,
      awayGaBefore: 1,
      actualHomeGoals: 2,
      actualAwayGoals: 0,
      actualOutcome: "home",
      bookmaker: "SyntheticBook",
      homeOdds: 1.2,
      drawOdds: 7,
      awayOdds: 13,
      oddsObservedAt: null,
      oddsTiming: "unknown",
    }),
    row({
      fixtureId: "syn-played-1-favorite-upset",
      kickoff: "2024-08-18T15:00:00.000Z",
      competitionId: "syn-league",
      competitionName: "Synthetic League",
      season: "2024",
      category: "womens",
      homeTeamId: "home-hot-2",
      homeTeamName: "Hot Home 2",
      awayTeamId: "away-dog",
      awayTeamName: "Dog Away",
      homePlayedBefore: 1,
      homeWinsBefore: 1,
      homeGfBefore: 3,
      homeGaBefore: 0,
      awayPlayedBefore: 1,
      awayWinsBefore: 0,
      awayGfBefore: 0,
      awayGaBefore: 3,
      actualHomeGoals: 0,
      actualAwayGoals: 1,
      actualOutcome: "away",
      bookmaker: "SyntheticBook",
      homeOdds: 1.25,
      drawOdds: 6,
      awayOdds: 11,
      oddsObservedAt: null,
      oddsTiming: "unknown",
    }),
    row({
      fixtureId: "syn-played-2-draw",
      kickoff: "2024-08-24T15:00:00.000Z",
      competitionId: "syn-league",
      competitionName: "Synthetic League",
      season: "2024",
      category: "mens",
      homeTeamId: "home-even",
      homeTeamName: "Even Home",
      awayTeamId: "away-even",
      awayTeamName: "Even Away",
      homePlayedBefore: 2,
      homeWinsBefore: 1,
      homeGfBefore: 2,
      homeGaBefore: 2,
      awayPlayedBefore: 2,
      awayWinsBefore: 1,
      awayGfBefore: 2,
      awayGaBefore: 2,
      actualHomeGoals: 1,
      actualAwayGoals: 1,
      actualOutcome: "draw",
      bookmaker: "SyntheticBook",
      homeOdds: 2.5,
      drawOdds: 3.2,
      awayOdds: 2.9,
      oddsObservedAt: null,
      oddsTiming: "unknown",
    }),
    row({
      fixtureId: "syn-played-5-home-win",
      kickoff: "2024-09-14T15:00:00.000Z",
      competitionId: "syn-league",
      competitionName: "Synthetic League",
      season: "2024",
      category: "international",
      homeTeamId: "home-mid",
      homeTeamName: "Mid Home",
      awayTeamId: "away-mid",
      awayTeamName: "Mid Away",
      homePlayedBefore: 5,
      homeWinsBefore: 3,
      homeGfBefore: 8,
      homeGaBefore: 5,
      awayPlayedBefore: 5,
      awayWinsBefore: 2,
      awayGfBefore: 5,
      awayGaBefore: 7,
      actualHomeGoals: 2,
      actualAwayGoals: 1,
      actualOutcome: "home",
      bookmaker: null,
      homeOdds: null,
      drawOdds: null,
      awayOdds: null,
      oddsObservedAt: null,
      oddsTiming: "unknown",
    }),
    row({
      fixtureId: "syn-played-10-away-win",
      kickoff: "2024-11-02T15:00:00.000Z",
      competitionId: "syn-league",
      competitionName: "Synthetic League",
      season: "2024",
      category: "mens",
      homeTeamId: "home-mature",
      homeTeamName: "Mature Home",
      awayTeamId: "away-mature",
      awayTeamName: "Mature Away",
      homePlayedBefore: 12,
      homeWinsBefore: 4,
      homeGfBefore: 12,
      homeGaBefore: 18,
      awayPlayedBefore: 12,
      awayWinsBefore: 8,
      awayGfBefore: 20,
      awayGaBefore: 10,
      actualHomeGoals: 0,
      actualAwayGoals: 2,
      actualOutcome: "away",
      bookmaker: "SyntheticBook",
      homeOdds: 3.4,
      drawOdds: 3.3,
      awayOdds: 2.15,
      oddsObservedAt: "2024-11-02T14:00:00.000Z",
      oddsTiming: "unknown",
    }),
    row({
      fixtureId: "syn-bangladesh-korea-shape",
      kickoff: "2025-07-01T12:00:00.000Z",
      competitionId: "syn-women",
      competitionName: "Synthetic Women",
      season: "2025",
      category: "womens",
      homeTeamId: "bd-w",
      homeTeamName: "Sparse Home",
      awayTeamId: "kr-w",
      awayTeamName: "Sparse Away",
      homePlayedBefore: 2,
      homeWinsBefore: 0,
      homeGfBefore: 0,
      homeGaBefore: 16,
      awayPlayedBefore: 2,
      awayWinsBefore: 2,
      awayGfBefore: 11,
      awayGaBefore: 0,
      actualHomeGoals: 0,
      actualAwayGoals: 3,
      actualOutcome: "away",
      bookmaker: "SyntheticBook",
      homeOdds: 9,
      drawOdds: 5.5,
      awayOdds: 1.3,
      oddsObservedAt: null,
      oddsTiming: "unknown",
    }),
  ];
}

export function createSyntheticLeagueFixtures(): ReconstructionFixture[] {
  return [
    {
      fixtureId: "lg-1",
      kickoff: "2024-08-01T15:00:00.000Z",
      competitionId: "syn-league",
      competitionName: "Synthetic League",
      season: "2024",
      homeTeamId: "alpha",
      homeTeamName: "Alpha",
      awayTeamId: "beta",
      awayTeamName: "Beta",
      status: "FT",
      goalsHome: 2,
      goalsAway: 0,
      fulltimeHome: 2,
      fulltimeAway: 0,
    },
    {
      fixtureId: "lg-pst",
      kickoff: "2024-08-05T15:00:00.000Z",
      competitionId: "syn-league",
      season: "2024",
      homeTeamId: "alpha",
      awayTeamId: "gamma",
      status: "PST",
      goalsHome: null,
      goalsAway: null,
      fulltimeHome: null,
      fulltimeAway: null,
    },
    {
      fixtureId: "lg-canc",
      kickoff: "2024-08-06T15:00:00.000Z",
      competitionId: "syn-league",
      season: "2024",
      homeTeamId: "alpha",
      awayTeamId: "gamma",
      status: "CANC",
      goalsHome: 3,
      goalsAway: 0,
      fulltimeHome: 3,
      fulltimeAway: 0,
    },
    {
      fixtureId: "lg-pen",
      kickoff: "2024-08-08T15:00:00.000Z",
      competitionId: "syn-league",
      season: "2024",
      homeTeamId: "gamma",
      awayTeamId: "alpha",
      status: "PEN",
      goalsHome: 1,
      goalsAway: 1,
      fulltimeHome: 1,
      fulltimeAway: 1,
    },
    {
      fixtureId: "lg-other-season",
      kickoff: "2023-08-01T15:00:00.000Z",
      competitionId: "syn-league",
      season: "2023",
      homeTeamId: "alpha",
      awayTeamId: "beta",
      status: "FT",
      goalsHome: 8,
      goalsAway: 0,
      fulltimeHome: 8,
      fulltimeAway: 0,
    },
    {
      fixtureId: "lg-future",
      kickoff: "2024-08-20T15:00:00.000Z",
      competitionId: "syn-league",
      season: "2024",
      homeTeamId: "alpha",
      awayTeamId: "beta",
      status: "FT",
      goalsHome: 5,
      goalsAway: 0,
      fulltimeHome: 5,
      fulltimeAway: 0,
    },
    {
      fixtureId: "lg-target",
      kickoff: "2024-08-10T15:00:00.000Z",
      competitionId: "syn-league",
      competitionName: "Synthetic League",
      season: "2024",
      homeTeamId: "alpha",
      homeTeamName: "Alpha",
      awayTeamId: "beta",
      awayTeamName: "Beta",
      status: "FT",
      goalsHome: 1,
      goalsAway: 0,
      fulltimeHome: 1,
      fulltimeAway: 0,
    },
  ];
}
